name: deploy

# Only run this when the main branch changes
on:
  push:
    branches:
    - main

# This job installs dependencies, build the site, and pushes it to pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    # Install python
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install python dependencies
      run: |
        python -m pip install -U pip
        python -m pip install -U flask
        python -m pip install -U flask_cors
        python -m pip install -U invoke


    # Build the site
    - name: Build the site
      run: |
        python -m invoke build

    # Push the page's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./poc
